SELECT U.ID, U.NAME, R.NAME AS ROLE, C.NAME AS COMPANY, E."startDate"
FROM USERS AS U
JOIN EXPERIENCES AS E ON E."userId" = U.ID
JOIN ROLES AS R ON R.ID = E."roleId"
JOIN COMPANIES AS C ON C.ID = E."companyId"
WHERE E."endDate" IS NULL AND U.ID = 50;
