SELECT U.ID, SCHOOL.NAME AS SCHOOL, COURSE.NAME AS COURSE, COMPANY.NAME AS COMPANY, R.NAME AS "ROLE"
FROM USERS AS U
JOIN EDUCATIONS AS EDUCATION ON EDUCATION."userId" = U.ID
JOIN COURSES AS COURSE ON COURSE.ID = EDUCATION."courseId"
JOIN SCHOOLS AS SCHOOL ON SCHOOL.ID = EDUCATION."schoolId"
JOIN APPLICANTS AS APPLICANT ON APPLICANT."userId" = U.ID
JOIN JOBS AS JOB ON JOB.ID = APPLICANT."jobId"
JOIN ROLES AS R ON R.NAME = 'Software Engineer'
JOIN COMPANIES AS COMPANY ON COMPANY.ID = JOB."companyId"
WHERE JOB.ACTIVE IS TRUE AND COMPANY.ID = 10;